name: ✨ Feature request
description: Suggest an idea for an improvement
body:
  - type: checkboxes
    id: initial-checklist
    attributes:
      label: I have a lot of issues to go through, so in order to make it easier for me to help you, I ask that you please try these things first
      options:
        - label: Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
          required: true
        - label: Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
          required: true
        - label: Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
          required: true
        - label: See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: A clear and concise description of what you want you would like to be added or improved in LosslessCut. You can attach screenshots or screencasts if needed.
    validations:
      required: true
