
// TODO
export const {
  getFfCommandLine,
  getFfmpegPath,
  getFfprobePath,
  runFfprobe,
  runFfmpeg,
  handleProgress,
  readFrames,
  getSafeCutTime,
  findNearestKeyFrameTime,
  tryReadChaptersToEdl,
  getFormatData,
  getDuration,
  createChaptersFromSegments,
  getDefaultOutFormat,
  getAllStreams,
  extractStreams,
  renderThumbnails,
  renderWaveformPng,
  extractWaveform,
  captureFrame,
  defaultProcessedCodecTypes,
  isMov,
  isStreamThumbnail,
  isAudioSupported,
  isIphoneHevc,
  getStreamFps,
  getOneRawFrame,
  encodeLiveRawStream,
  getTimecodeFromStreams,
} = window.ffmpeg;
