export const homepageUrl = 'https://mifi.no/losslesscut/';
export const githubUrl = 'https://github.com/mifi/lossless-cut/';
export const getReleaseUrl = (version: string) => `https://github.com/mifi/lossless-cut/releases/tag/v${version}`;
export const compareReleasesUrl = (fromVersion: string, toVersion: string) => `https://github.com/mifi/lossless-cut/compare/v${fromVersion}...v${toVersion}`;
export const licensesUrl = 'https://losslesscut.mifi.no/licenses.txt';
export const thanksUrl = 'https://mifi.no/thanks';
export const issuesUrl = 'https://github.com/mifi/lossless-cut/issues';
export const discussionsUrl = 'https://github.com/mifi/lossless-cut/discussions';
export const usageUrl = 'https://mifi.no/losslesscut/usage';
export const faqUrl = 'https://mifi.no/losslesscut/faq';
export const troubleshootingUrl = 'https://mifi.no/losslesscut/troubleshooting';
export const exportedFileNameTemplateHelpUrl = 'https://github.com/mifi/lossless-cut/blob/master/docs.md#custom-exported-file-names';
export const jsExpressionHelpUrl = 'https://github.com/mifi/lossless-cut/blob/master/expressions.md';
export const supportEmail = 'losslesscut@mifi.no';
